<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Application.Adapters\Core.Application.Adapters.Http.csproj" />
		<ProjectReference Include="..\Core.Application.ComandQueryBus\Core.Application.ComandQueryBus.csproj" />
		<ProjectReference Include="..\Core.Application.EventBus\Core.Application.EventBus.csproj" />
		<ProjectReference Include="..\Core.Application.Mapping\Core.Application.Mapping.csproj" />
		<ProjectReference Include="..\Core.Application.Repositories\Core.Application.Repositories.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="ActividadMuseo\UseCases\ActividadesMuseo\Notifications\" />
		<Folder Include="Adapters\" />
		<Folder Include="Common\UseCases\Provincia\Commands\" />
		<Folder Include="Common\UseCases\Provincia\Notifications\" />
		<Folder Include="MuseumResources\UseCases\MuseumGallery\Queries\NewFolder\" />
		<Folder Include="VisitaGrupal\UseCases\Commands\DeleteTurnosVisitas\" />
		<Folder Include="VisitaGrupal\UseCases\Commands\UpdateTurnosVisitas\" />
		<Folder Include="VisitaGrupal\UseCases\Notification\" />
		<Folder Include="VisitaGrupal\UseCases\Queries\GetTurnosVisitas\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="AutoMapper" Version="16.1.1" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
      <PackageReference Include="Scrutor" Version="7.0.0" />
	</ItemGroup>

</Project>
