// <auto-generated />
using System;
using Infrastructure.Repositories.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MuseoDbContext))]
    [Migration("20251213034239_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.CommonDomain.Entities.DummyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DummyPropertyOne")
                        .HasColumnType("longtext");

                    b.Property<int>("DummyPropertyTwo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DummyEntity", (string)null);
                });

            modelBuilder.Entity("Domain.UsuarioVisitante.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UsuarioVisitante", (string)null);
                });

            modelBuilder.Entity("Domain.UsuarioVisitante.Entities.Usuario", b =>
                {
                    b.OwnsOne("Domain.CommonDomain.ValueObjets.Email", "EmailVisitante", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("EmailVisitante");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("UsuarioVisitante");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Domain.CommonDomain.ValueObjets.Telefono", "TelefonoVisitante", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("NumeroNormalizado")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("TelefonoVisitante");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("UsuarioVisitante");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Domain.UsuarioVisitante.ValueObjets.EmailToken", "TokenConfirmacion", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ExpiracionUtc")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("TokenExpiracion");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("TokenConfirmacion");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("UsuarioVisitante");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Domain.UsuarioVisitante.ValueObjets.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("UsuarioVisitante");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("EmailVisitante");

                    b.Navigation("PasswordHash");

                    b.Navigation("TelefonoVisitante");

                    b.Navigation("TokenConfirmacion");
                });
#pragma warning restore 612, 618
        }
    }
}
