// <auto-generated />
using System;
using Infrastructure.Repositories.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MuseoDbContext))]
    [Migration("20260808162340_ConfiguracionAutoguiadanintervalosescalonados")]
    partial class ConfiguracionAutoguiadanintervalosescalonados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ActividadSala", b =>
                {
                    b.Property<int>("ActividadMuseoId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("ActividadMuseoId", "SalaId");

                    b.HasIndex("SalaId");

                    b.ToTable("ActividadSalas", (string)null);
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.ActividadMuseo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("CategoriaActividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoActividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ActividadesMuseo", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.BloqueoSala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("BloqueosSala", (string)null);
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.CalendarioMuseo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("CalendariosMuseo", (string)null);
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.DiaCierreMuseo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarioMuseoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioMuseoId");

                    b.ToTable("diascierremuseo", (string)null);
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.RecursoAsignado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadAsignada")
                        .HasColumnType("int");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("RecursoId");

                    b.ToTable("ActividadRecursosAsignados", (string)null);
                });

            modelBuilder.Entity("Domain.Common.Entities.Departamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProvinciaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId", "Nombre");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("Domain.Common.Entities.DummyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DummyPropertyOne")
                        .HasColumnType("longtext");

                    b.Property<int>("DummyPropertyTwo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DummyEntity", (string)null);
                });

            modelBuilder.Entity("Domain.Common.Entities.Localidad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DepartamentoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProvinciaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("ProvinciaId", "DepartamentoId", "Nombre");

                    b.ToTable("Localidades", (string)null);
                });

            modelBuilder.Entity("Domain.Common.Entities.Provincia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Provincias", (string)null);
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Guia.AusenciaGuia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GuiaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.ToTable("AusenciasGuia", (string)null);
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Guia.Guia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PersonalInternoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Guias", (string)null);
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Guia.HorarioGuia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuiaId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.ToTable("HorariosGuia", (string)null);
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreRecurso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Recursos", (string)null);
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoSala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoSala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Salas", (string)null);
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.ConfiguracionHorarioAutoguiada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadMaximaPorGrupo")
                        .HasColumnType("int");

                    b.Property<long>("DuracionVisita")
                        .HasColumnType("bigint");

                    b.Property<long>("IntervaloReservas")
                        .HasColumnType("bigint");

                    b.Property<int>("VisitasSimultaneasMaximas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionVisitaAutoguiada", (string)null);
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.ConfiguracionVisitasGrupalesGuiadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadMaximaPorTurno")
                        .HasColumnType("int");

                    b.Property<int>("CapacidadPorGuia")
                        .HasColumnType("int");

                    b.Property<int>("MinGuiasParaCapacidadCompleta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionVisitasGrupalesGuiadas", (string)null);
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.TematicaVisita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TematicasVisita", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Identity.UsuarioSistema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TematicaSala", b =>
                {
                    b.Property<int>("TematicaVisitaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("TematicaVisitaId", "SalaId");

                    b.HasIndex("SalaId");

                    b.ToTable("TematicaSalas", (string)null);
                });

            modelBuilder.Entity("VisitaGuiadaTematicas", b =>
                {
                    b.Property<int>("VisitaGrupalGuiadaId")
                        .HasColumnType("int");

                    b.Property<int>("TematicaId")
                        .HasColumnType("int");

                    b.HasKey("VisitaGrupalGuiadaId", "TematicaId");

                    b.HasIndex("TematicaId");

                    b.ToTable("VisitaGuiadaTematicas");
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.VisitaGrupalAutoguiada", b =>
                {
                    b.HasBaseType("Domain.ActividadMuseo.Entities.ActividadMuseo");

                    b.Property<string>("DepartamentoInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DiversidadFuncional")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EstadoConfirmacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LocalidadInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ProvinciaInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioVisitanteId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("VisitasGrupalesAutoguiadas", (string)null);
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.VisitaGrupalGuiada", b =>
                {
                    b.HasBaseType("Domain.ActividadMuseo.Entities.ActividadMuseo");

                    b.Property<int?>("AnioGrado")
                        .HasColumnType("int");

                    b.Property<string>("DepartamentoInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DiversidadFuncionalDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EstadoConfirmacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LocalidadInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MotivoRelacionVisita")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ProvinciaInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioVisitanteId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("VisitasGrupalesGuiadas", (string)null);
                });

            modelBuilder.Entity("ActividadSala", b =>
                {
                    b.HasOne("Domain.ActividadMuseo.Entities.ActividadMuseo", null)
                        .WithMany()
                        .HasForeignKey("ActividadMuseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.RecursoMuseo.Entities.Sala", null)
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.ActividadMuseo", b =>
                {
                    b.OwnsMany("Domain.Common.ValueObjets.TimeSlot", "TimeSlots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ActividadMuseoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("datetime");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("datetime");

                            b1.HasKey("Id");

                            b1.HasIndex("ActividadMuseoId");

                            b1.ToTable("ActividadTimeSlots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ActividadMuseoId");
                        });

                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.BloqueoSala", b =>
                {
                    b.HasOne("Domain.RecursoMuseo.Entities.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.CalendarioMuseo", b =>
                {
                    b.OwnsOne("Domain.ActividadMuseo.ValueObjets.DiasLaboralesMuseo", "DiasApertura", b1 =>
                        {
                            b1.Property<int>("CalendarioMuseoId")
                                .HasColumnType("int");

                            b1.Property<string>("Dias")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("DiasApertura");

                            b1.HasKey("CalendarioMuseoId");

                            b1.ToTable("CalendariosMuseo");

                            b1.WithOwner()
                                .HasForeignKey("CalendarioMuseoId");
                        });

                    b.OwnsOne("Domain.ActividadMuseo.ValueObjets.Horario", "HorarioApertura", b1 =>
                        {
                            b1.Property<int>("CalendarioMuseoId")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time(6)")
                                .HasColumnName("HoraFin");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time(6)")
                                .HasColumnName("HoraInicio");

                            b1.HasKey("CalendarioMuseoId");

                            b1.ToTable("CalendariosMuseo");

                            b1.WithOwner()
                                .HasForeignKey("CalendarioMuseoId");
                        });

                    b.Navigation("DiasApertura");

                    b.Navigation("HorarioApertura");
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.DiaCierreMuseo", b =>
                {
                    b.HasOne("Domain.ActividadMuseo.Entities.CalendarioMuseo", null)
                        .WithMany("DiasCierre")
                        .HasForeignKey("CalendarioMuseoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.RecursoAsignado", b =>
                {
                    b.HasOne("Domain.ActividadMuseo.Entities.ActividadMuseo", "Actividad")
                        .WithMany("Recursos")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.RecursoMuseo.Entities.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Domain.Common.Entities.Departamento", b =>
                {
                    b.HasOne("Domain.Common.Entities.Provincia", null)
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Common.Entities.Localidad", b =>
                {
                    b.HasOne("Domain.Common.Entities.Departamento", null)
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Common.Entities.Provincia", null)
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Guia.AusenciaGuia", b =>
                {
                    b.HasOne("Domain.RecursoMuseo.Entities.Guia.Guia", "Guia")
                        .WithMany("AusenciasProgramadas")
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Guia.HorarioGuia", b =>
                {
                    b.HasOne("Domain.RecursoMuseo.Entities.Guia.Guia", "Guia")
                        .WithMany("HorariosGuia")
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.RecursoMuseo.ValueObjets.DiaLaboral", "DiaAsignado", b1 =>
                        {
                            b1.Property<int>("HorarioGuiaId")
                                .HasColumnType("int");

                            b1.Property<string>("Dia")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.HasKey("HorarioGuiaId");

                            b1.ToTable("HorariosGuia");

                            b1.WithOwner()
                                .HasForeignKey("HorarioGuiaId");
                        });

                    b.Navigation("DiaAsignado");

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.ConfiguracionHorarioAutoguiada", b =>
                {
                    b.OwnsOne("Domain.ActividadMuseo.ValueObjets.DiasLaboralesMuseo", "DiasDisponibles", b1 =>
                        {
                            b1.Property<int>("ConfiguracionHorarioAutoguiadaId")
                                .HasColumnType("int");

                            b1.Property<string>("Dias")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("DiasDisponibles");

                            b1.HasKey("ConfiguracionHorarioAutoguiadaId");

                            b1.ToTable("ConfiguracionVisitaAutoguiada");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracionHorarioAutoguiadaId");
                        });

                    b.OwnsOne("Domain.ActividadMuseo.ValueObjets.Horario", "HorarioDisponibleVisitaAutoguiadas", b1 =>
                        {
                            b1.Property<int>("ConfiguracionHorarioAutoguiadaId")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time(6)")
                                .HasColumnName("HoraFin");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time(6)")
                                .HasColumnName("HoraInicio");

                            b1.HasKey("ConfiguracionHorarioAutoguiadaId");

                            b1.ToTable("ConfiguracionVisitaAutoguiada");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracionHorarioAutoguiadaId");
                        });

                    b.OwnsMany("Domain.VisitasGrupales.ValueObjects.BloqueoAutoguiada", "Bloqueos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ConfiguracionHorarioAutoguiadaId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("FechaDesde")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("FechaDesde");

                            b1.Property<DateTime>("FechaHasta")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("FechaHasta");

                            b1.Property<string>("Motivo")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("Motivo");

                            b1.HasKey("Id");

                            b1.HasIndex("ConfiguracionHorarioAutoguiadaId");

                            b1.ToTable("BloqueosVisitasAutoguiadas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracionHorarioAutoguiadaId");
                        });

                    b.Navigation("Bloqueos");

                    b.Navigation("DiasDisponibles");

                    b.Navigation("HorarioDisponibleVisitaAutoguiadas");
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.ConfiguracionVisitasGrupalesGuiadas", b =>
                {
                    b.OwnsOne("Domain.ActividadMuseo.ValueObjets.DiasLaboralesMuseo", "DiasDisponibles", b1 =>
                        {
                            b1.Property<int>("ConfiguracionVisitasGrupalesGuiadasId")
                                .HasColumnType("int");

                            b1.Property<string>("Dias")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("DiasDisponibles");

                            b1.HasKey("ConfiguracionVisitasGrupalesGuiadasId");

                            b1.ToTable("ConfiguracionVisitasGrupalesGuiadas");

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracionVisitasGrupalesGuiadasId");
                        });

                    b.OwnsMany("Domain.VisitasGrupales.ValueObjects.BloqueoVisitasGuiadas", "Bloqueos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ConfiguracionVisitasGrupalesGuiadasId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("FechaDesde")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime>("FechaHasta")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("Motivo")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("ConfiguracionVisitasGrupalesGuiadasId");

                            b1.ToTable("BloqueosVisitasGuiadas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracionVisitasGrupalesGuiadasId");
                        });

                    b.OwnsMany("Domain.VisitasGrupales.ValueObjects.TurnoVisitaGuiada", "Turnos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ConfiguracionVisitasGrupalesGuiadasId")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("HoraFin")
                                .HasColumnType("time(6)")
                                .HasColumnName("HoraFin");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time(6)")
                                .HasColumnName("HoraInicio");

                            b1.HasKey("Id");

                            b1.HasIndex("ConfiguracionVisitasGrupalesGuiadasId");

                            b1.ToTable("TurnosVisitasGuiadas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConfiguracionVisitasGrupalesGuiadasId");
                        });

                    b.Navigation("Bloqueos");

                    b.Navigation("DiasDisponibles");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.Identity.UsuarioSistema", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TematicaSala", b =>
                {
                    b.HasOne("Domain.RecursoMuseo.Entities.Sala", null)
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.VisitasGrupales.Entities.TematicaVisita", null)
                        .WithMany()
                        .HasForeignKey("TematicaVisitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VisitaGuiadaTematicas", b =>
                {
                    b.HasOne("Domain.VisitasGrupales.Entities.TematicaVisita", null)
                        .WithMany()
                        .HasForeignKey("TematicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.VisitasGrupales.Entities.VisitaGrupalGuiada", null)
                        .WithMany()
                        .HasForeignKey("VisitaGrupalGuiadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.VisitaGrupalAutoguiada", b =>
                {
                    b.HasOne("Domain.ActividadMuseo.Entities.ActividadMuseo", null)
                        .WithOne()
                        .HasForeignKey("Domain.VisitasGrupales.Entities.VisitaGrupalAutoguiada", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Common.ValueObjets.Email", "EmailInstitucion", b1 =>
                        {
                            b1.Property<int>("VisitaGrupalAutoguiadaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("EmailInstitucion");

                            b1.HasKey("VisitaGrupalAutoguiadaId");

                            b1.ToTable("VisitasGrupalesAutoguiadas");

                            b1.WithOwner()
                                .HasForeignKey("VisitaGrupalAutoguiadaId");
                        });

                    b.Navigation("EmailInstitucion");
                });

            modelBuilder.Entity("Domain.VisitasGrupales.Entities.VisitaGrupalGuiada", b =>
                {
                    b.HasOne("Domain.ActividadMuseo.Entities.ActividadMuseo", null)
                        .WithOne()
                        .HasForeignKey("Domain.VisitasGrupales.Entities.VisitaGrupalGuiada", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Common.ValueObjets.Telefono", "TelefonoInstitucion", b1 =>
                        {
                            b1.Property<int>("VisitaGrupalGuiadaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("TelefonoInstitucion");

                            b1.HasKey("VisitaGrupalGuiadaId");

                            b1.ToTable("VisitasGrupalesGuiadas");

                            b1.WithOwner()
                                .HasForeignKey("VisitaGrupalGuiadaId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjets.Email", "EmailInstitucion", b1 =>
                        {
                            b1.Property<int>("VisitaGrupalGuiadaId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("EmailInstitucion");

                            b1.HasKey("VisitaGrupalGuiadaId");

                            b1.ToTable("VisitasGrupalesGuiadas");

                            b1.WithOwner()
                                .HasForeignKey("VisitaGrupalGuiadaId");
                        });

                    b.Navigation("EmailInstitucion");

                    b.Navigation("TelefonoInstitucion");
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.ActividadMuseo", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Domain.ActividadMuseo.Entities.CalendarioMuseo", b =>
                {
                    b.Navigation("DiasCierre");
                });

            modelBuilder.Entity("Domain.RecursoMuseo.Entities.Guia.Guia", b =>
                {
                    b.Navigation("AusenciasProgramadas");

                    b.Navigation("HorariosGuia");
                });
#pragma warning restore 612, 618
        }
    }
}
